version: '3.8'

services:
  glossary-ai-web-frontend-stage:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TS_WEBAPP_BUILD_VARIANT: ${TS_WEBAPP_BUILD_VARIANT}
        TS_WEBAPP_PROXY_CONNECTION_STRING: ${TS_WEBAPP_PROXY_CONNECTION_STRING}
    container_name: ts-v2-webapp-stage
    ports:
      - "23000:3000" 
    image: glossary-ai-web-frontend-stage:2026.05.13.1
    restart: unless-stopped
