services:
  glossary-ai-web-staging:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GLOSSARYAI_WEBAPP_BUILD_VARIANT: ${GLOSSARYAI_WEBAPP_BUILD_VARIANT:-build_without_proxy}
        GLOSSARYAI_WEBAPP_PROXY_CONNECTION_STRING: ${GLOSSARYAI_WEBAPP_PROXY_CONNECTION_STRING:-}
    image: glossary-ai-web-staging:latest
    container_name: glossary-ai-web-staging
    env_file:
      - .env
    environment:
      HOSTNAME: 0.0.0.0
      PORT: 3000
    ports:
      - "23000:3000"
    restart: unless-stopped
